require 'pod/command/package'
require 'cocoapods-pack/user_interface/build_failed_report'
require 'cocoapods-pack/builder'
require 'cocoapods-pack/framework'
require 'cocoapods-pack/mangle'
require 'cocoapods-pack/pod_utils'
require 'cocoapods-pack/spec_builder'
require 'cocoapods-pack/symbols'
